from arq_package.mod_produtos import produtos
from arq_package.mod_org1 import organizador_por_preco
from arq_package.mod_org2 import organizador_por_nome
from arq_package.mod_preco import alteracao_de_preco
from arq_package.mod_mostrar import mostrar_lista_de_dicts